# Generated by Django 5.2.6 on 2025-10-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('rol', models.CharField(max_length=10)),
                ('password_hash', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='reservar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('adultos', models.PositiveSmallIntegerField(default=1)),
                ('ninos', models.PositiveSmallIntegerField(default=0)),
                ('mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
    ]
