# Generated by Django 5.2.6 on 2025-10-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('rol', models.CharField(max_length=10)),
                ('password_hash', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
